<?php

namespace RestBundle\Repository;

/**
 * AccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedArtistComposerRepository extends \Doctrine\ORM\EntityRepository
{

	/* @FunctionName : getFeaturedArtists
    * @Desc         : get list of featured artist and composer
    * 
    * @return Array
    */
	public function getFeaturedArtists($territory)
	{
  		$language = 'EN';
  		$limit = 20;

		$qb = $this->createQueryBuilder('FA')
				->where('FA.territory = :territory')
				->andWhere('FA.language = :language')
				->setParameter('territory', $territory)
				->setParameter('language', $language)
				->orderBy('FA.id', 'ASC')
				->setMaxResults($limit)
				->getQuery();

		return $qb->getArrayResult();
	}


	/* @FunctionName : checkImageFileExist
    * @Desc         : check the images exist or not using CURL
    * 
    * @param ImageURL String 
    * @return Boolean
    */
    function checkImageFileExist($imageURL) {      
     
      return true;
    }


    
}
