<?php

namespace RestBundle\Repository;

/**
 * AccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedArtistComposerRepository extends \Doctrine\ORM\EntityRepository
{

	/* @FunctionName : getFeaturedArtists
   * @Desc         : get list of featured artist and composer
   * 
   * @return Array
   */
	public function getFeaturedArtists($territory)
	{
  		$language = 'EN';
  		$limit = 20;
      
  		$qb = $this->createQueryBuilder('FA')
  				->where('FA.territory = :territory')
  				->andWhere('FA.language = :language')
  				->setParameter('territory', $territory)
  				->setParameter('language', $language)
  				->orderBy('FA.id', 'ASC')
  				->setMaxResults($limit)
  				->getQuery();

    $result =  $qb->getArrayResult(); 
    
    if(empty($result))    
      $result = array( '204' => 'No Content Found' );    
 
    return $result;
	}


	/* @FunctionName : checkImageFileExist
   * @Desc         : check the images exist or not using CURL
   * 
   * @param ImageURL String 
   * @return Boolean
   */
    function checkImageFileExist($imageURL) {      
     
   
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL,$imageURL);
      // don't download content
      curl_setopt($ch, CURLOPT_NOBODY, 1);
      curl_setopt($ch, CURLOPT_FAILONERROR, 1);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      if(curl_exec($ch)!==FALSE) {
          return true;
      }else{
          return false;
      }      
       
      //return true;
    }


    
}
