<?php

namespace RestBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
*TerritoriesRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/

class TerritoriesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * This function is used to get Top getAllTerritory
     *
     * @return   Array Data
     */

    public function getAllTerritory()
    {
        $allTerritory = $this->createQueryBuilder('e')
           ->select('e.territory')
           ->getQuery()
           ->getArrayResult();
        return $allTerritory;
    }
}
