<?php

namespace RestBundle\Repository;

/**
 * TopAlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopAlbumsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopAlbumsList($territory)
    {
        $language = 'EN';
        $limit = 5;
        $query = $this->createQueryBuilder('TA')
                ->where('TA.territory = :territory')
                ->andWhere('TA.language= :language')
                ->setParameter('territory',$territory)
                ->setParameter('language',$language)
                ->orderBy('TA.sortid', 'ASC')
                ->setMaxResults( $limit )
                ->getQuery();

        $topAlbumsList = $query->getResult();

        return $topAlbumsList;
    }

}
